name: nep_sin_offline_translator
description: Offline Nepali/Sinhalese to English OCR + Translation (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tesseract_ocr: ^0.4.23
  image_picker: ^1.1.2
  camera: ^0.11.0
  path_provider: ^2.1.4
  onnxruntime: ^1.17.6
  share_plus: ^10.0.2
  clipboard: ^0.1.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata/nep.traineddata
    - assets/tessdata/sin.traineddata
    - assets/tessdata/eng.traineddata
    - assets/models/ne_en/model.onnx
    - assets/models/ne_en/spm.model
    - assets/models/ne_en/vocab.json
    - assets/models/si_en/model.onnx
    - assets/models/si_en/spm.model
    - assets/models/si_en/vocab.json


